### ISSUE TITLE
Slug should refer to the filename, not the slugified title

### ISSUE THREAD

**Issue by belak** [golf1052/base16-builder-typescript#1]
This was changed in 0.8.1.

Once that's done, I think this is up to compliance with 0.9.0.

**Comment by golf1052** [comment]
So in [Template Variables](https://github.com/chriskempson/base16/blob/master/builder.md#template-variables) `scheme-slug` should say

>obtained from scheme filename

instead?

Looks like it's correct earlier in Workflow

>The theme filename should look like `base16-[slug][extension]`. Where the slug is taken from the scheme file name made lowercase with spaces replaced with dashes

**Comment by belak** [comment]
Yes, I believe that's correct. I'll open a PR against that repo for clarification.

https://github.com/chriskempson/base16/issues/78 was where it was discussed, as far as I know.

**Comment by belak** [comment]
I've opened https://github.com/chriskempson/base16/pull/107 to make it a little clearer

**Comment by golf1052** [comment]
Just pushed 1.1.1 to fix this (bc410b07abcb5d7a881e67eeaac9b4dc7f525593)

**Comment by belak** [comment]
Awesome, I updated https://github.com/chriskempson/base16/pull/106 to show that you're up to date. :)
