### ISSUE TITLE
npm package has DOS line endings

### ISSUE THREAD

**Issue by ghost** [golf1052/base16-builder-typescript#2]
The npm package seems to have DOS line endings, which is messing with the shebang [here](https://github.com/golf1052/base16-builder-typescript/blob/6e9185ad0dd258a45026aafb1928f0e2ba81c868/bin/main.js#L1). When trying to execute it as a binary the error `/usr/bin/env: ‘node\r’: No such file or directory` is thrown.

Not the case if I clone directly from this repo though.

**Comment by golf1052** [comment]
Just pushed 1.1.3 that should fix this issue. Can you try and report back?

**Comment by ghost** [comment]
Fixed 👍
